services:
  - type: web
    name: anazah-spices-shop
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: docker-compose up
    envVars:
      - key: WORDPRESS_DB_HOST
        value: db
      - key: WORDPRESS_DB_NAME
        value: wordpress
      - key: WORDPRESS_DB_USER
        value: wordpress_user
      - key: WORDPRESS_DB_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: wordpress
      - key: MYSQL_USER
        value: wordpress_user
      - key: MYSQL_PASSWORD
        generateValue: true

databases:
  - name: wordpress-db
    databaseName: wordpress
    user: wordpress_user

